export interface PlatformPreset {
  id: string;
  name: string;
  exportHint: string;
  // ORDER_FIELDS key -> known real header strings for this platform's typical order export.
  headerSynonyms: Partial<Record<string, string[]>>;
}

// Best-effort common header names for each platform's typical order export. Real exports vary
// by store configuration, app/plugin used, and date - these are a head start, not a guarantee.
// The generic autoDetectMapping fallback (via detectMappingForPlatform below) catches anything
// a preset doesn't recognize, and every suggestion stays editable on the mapping screen.
export const PLATFORM_PRESETS: PlatformPreset[] = [
  {
    id: "shopify",
    name: "Shopify",
    exportHint: "Settings → Export orders → CSV for all orders",
    headerSynonyms: {
      orderNumber: ["name"],
      orderDate: ["created at"],
      currency: ["currency"],
      tags: ["tags"],
      note: ["notes"],
      email: ["email"],
      phone: ["phone"],
      firstName: ["shipping name", "billing name"],
      address1: ["shipping address1"],
      address2: ["shipping address2"],
      city: ["shipping city"],
      province: ["shipping province"],
      zip: ["shipping zip"],
      country: ["shipping country"],
      billingAddress1: ["billing address1"],
      billingAddress2: ["billing address2"],
      billingCity: ["billing city"],
      billingProvince: ["billing province"],
      billingZip: ["billing zip"],
      billingCountry: ["billing country"],
      sku: ["lineitem sku"],
      productTitle: ["lineitem name"],
      quantity: ["lineitem quantity"],
      lineItemPrice: ["lineitem price"],
      lineDiscount: ["lineitem discount"],
      subtotal: ["subtotal"],
      shippingCost: ["shipping"],
      tax: ["taxes"],
      total: ["total"],
      discountTotal: ["discount amount"],
      financialStatus: ["financial status"],
    },
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    exportHint: "WooCommerce → Orders → Export (CSV)",
    headerSynonyms: {
      orderNumber: ["order number"],
      orderDate: ["order date"],
      email: ["billing email"],
      firstName: ["billing first name"],
      lastName: ["billing last name"],
      phone: ["billing phone"],
      company: ["shipping company"],
      note: ["customer note"],
      address1: ["shipping address 1"],
      address2: ["shipping address 2"],
      city: ["shipping city"],
      province: ["shipping state/county", "shipping state"],
      zip: ["shipping postcode"],
      country: ["shipping country"],
      billingAddress1: ["billing address 1"],
      billingAddress2: ["billing address 2"],
      billingCity: ["billing city"],
      billingProvince: ["billing state/county", "billing state"],
      billingZip: ["billing postcode"],
      billingCountry: ["billing country"],
      billingCompany: ["billing company"],
      sku: ["sku", "item sku"],
      productTitle: ["item name"],
      quantity: ["quantity", "item quantity"],
      lineItemPrice: ["item cost"],
      subtotal: ["order subtotal amount"],
      shippingCost: ["order shipping amount"],
      tax: ["order total tax amount"],
      total: ["order total amount"],
      discountTotal: ["cart discount amount", "coupon amount"],
      financialStatus: ["status", "order status"],
    },
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    exportHint: "Orders → Export orders (CSV)",
    headerSynonyms: {
      orderNumber: ["order id"],
      orderDate: ["order date"],
      email: ["customer email"],
      firstName: ["customer first name"],
      lastName: ["customer last name"],
      sku: ["product sku"],
      productTitle: ["product name"],
      quantity: ["product quantity"],
      lineItemPrice: ["product price"],
      subtotal: ["order subtotal"],
      shippingCost: ["shipping cost"],
      total: ["order total"],
      address1: ["shipping address"],
      city: ["shipping city"],
      province: ["shipping state"],
      zip: ["shipping zip"],
      country: ["shipping country"],
      billingAddress1: ["billing address"],
      billingCity: ["billing city"],
      billingProvince: ["billing state"],
      billingZip: ["billing zip"],
      billingCountry: ["billing country"],
      financialStatus: ["order status"],
    },
  },
  {
    id: "wix",
    name: "Wix",
    exportHint: "Store Orders → Export CSV",
    headerSynonyms: {
      orderNumber: ["order number"],
      orderDate: ["order date"],
      firstName: ["recipient name"],
      email: ["email"],
      phone: ["phone"],
      address1: ["address"],
      city: ["city"],
      province: ["state"],
      zip: ["zip code"],
      country: ["country"],
      sku: ["sku"],
      productTitle: ["item(s)", "items"],
      quantity: ["quantity"],
      lineItemPrice: ["price"],
      total: ["total"],
      financialStatus: ["payment status"],
    },
  },
  {
    id: "squarespace",
    name: "Squarespace",
    exportHint: "Commerce → Orders → Export (CSV)",
    headerSynonyms: {
      orderNumber: ["order id"],
      orderDate: ["created at"],
      email: ["email"],
      firstName: ["billing name"],
      currency: ["currency"],
      address1: ["shipping address1"],
      city: ["shipping city"],
      province: ["shipping province"],
      zip: ["shipping zip"],
      country: ["shipping country"],
      sku: ["lineitem sku"],
      productTitle: ["lineitem name"],
      quantity: ["lineitem quantity"],
      lineItemPrice: ["lineitem price"],
      subtotal: ["subtotal"],
      shippingCost: ["shipping"],
      tax: ["taxes"],
      discountTotal: ["discount"],
      total: ["total"],
      financialStatus: ["financial status"],
    },
  },
  {
    id: "adobe_commerce",
    name: "Adobe Commerce (Magento)",
    exportHint: "Sales → Orders → Export (CSV)",
    headerSynonyms: {
      orderNumber: ["order #", "increment id"],
      orderDate: ["purchase date"],
      email: ["customer email"],
      firstName: ["bill-to name"],
      total: ["grand total (base)"],
      financialStatus: ["status"],
      currency: ["order currency"],
      shippingCost: ["shipping and handling"],
      subtotal: ["subtotal"],
      address1: ["shipping address"],
      billingAddress1: ["billing address"],
      sku: ["sku"],
      quantity: ["qty", "qty ordered"],
    },
  },
  {
    id: "amazon",
    name: "Amazon",
    exportHint: "Seller Central → Reports → Order data export",
    headerSynonyms: {
      orderNumber: ["order id", "amazon order id"],
      orderDate: ["purchase date"],
      email: ["buyer email"],
      firstName: ["buyer name", "recipient name"],
      phone: ["buyer phone number"],
      sku: ["sku"],
      productTitle: ["product name"],
      quantity: ["quantity purchased"],
      lineItemPrice: ["item price"],
      tax: ["item tax"],
      shippingCost: ["shipping price"],
      currency: ["currency"],
      address1: ["ship address 1"],
      address2: ["ship address 2"],
      city: ["ship city"],
      province: ["ship state"],
      zip: ["ship postal code"],
      country: ["ship country"],
      financialStatus: ["order status"],
    },
  },
  {
    id: "etsy",
    name: "Etsy",
    exportHint: "Shop Manager → Settings → Options → Download Data (Orders CSV)",
    headerSynonyms: {
      orderNumber: ["order id"],
      orderDate: ["sale date", "date paid"],
      productTitle: ["item name"],
      firstName: ["buyer", "ship name"],
      quantity: ["quantity"],
      lineItemPrice: ["price"],
      shippingCost: ["shipping"],
      tax: ["sales tax"],
      total: ["order total"],
      discountTotal: ["discount amount"],
      currency: ["currency"],
      address1: ["ship address1"],
      address2: ["ship address2"],
      city: ["ship city"],
      province: ["ship state"],
      zip: ["ship zip"],
      country: ["ship country"],
      sku: ["sku"],
    },
  },
];

export function getPlatformPreset(id: string | null | undefined): PlatformPreset | undefined {
  if (!id) return undefined;
  return PLATFORM_PRESETS.find((p) => p.id === id);
}
