# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f42fcdb20fd0579980f6dbcc6991508"
name = "OrderLink Up"
handle = "orderlink-up"
application_url = "https://orderlink-up-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_orders,write_draft_orders"

[auth]
redirect_urls = [ "https://orderlink-up-production.up.railway.app/auth/callback" ]
